name: Screenshot
on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight every day

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Metrics and Screenshot
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.pagespeed.screenshot.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://www.information.coffee
